<a href="https://colab.research.google.com/github/Edwinshajan2006/data-science-/blob/main/PANDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#!pip   install pandas

In [5]:
import pandas as pd
import numpy as np

In [6]:

df = pd.read_excel("/content/students_eda_dataset.xlsx")

In [7]:
# Q1 A

df.head()

,student_id,name,gender,department,attendance,marks,age,semester,city,scholarship
0,1,Rahul,Male,Mechanical,95,NaN,NaN,5,Thrissur,No
1,2,Anu,Male,Civil,62,NaN,18.0,1,Calicut,No
2,3,Vishnu,Male,Computer Science,90,36.0,NaN,1,Calicut,Yes
3,4,Sachin,Male,Computer Science,85,90.0,23.0,5,Kochi,No
4,5,Vimal,Female,Civil,99,NaN,NaN,1,Trivandrum,Yes

In [8]:
#Q1 B

df.tail()

,student_id,name,gender,department,attendance,marks,age,semester,city,scholarship
45,46,Vimal,Female,Mechanical,85,77.0,NaN,2,Kochi,Yes
46,47,Neha,Male,Civil,60,NaN,25.0,1,Calicut,Yes
47,48,Arjun,Male,Civil,73,36.0,25.0,6,Thrissur,No
48,49,Vimal,Female,Mechanical,80,74.0,25.0,4,Trivandrum,Yes
49,50,Pooja,Male,Electrical,62,NaN,NaN,4,Trivandrum,Yes

In [10]:
#Q1 C

df.shape

(50, 10)

In [11]:
#2 a
df.dtypes

student_id       int64
name            object
gender          object
department      object
attendance       int64
marks          float64
age            float64
semester         int64
city            object
scholarship     object
dtype: object

In [14]:
#2 b
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   student_id   50 non-null     int64
 1   name         50 non-null     object
 2   gender       50 non-null     object
 3   department   50 non-null     object
 4   attendance   50 non-null     int64
 5   marks        24 non-null     float64
 6   age          28 non-null     float64
 7   semester     50 non-null     int64
 8   city         50 non-null     object
 9   scholarship  50 non-null     object
dtypes: float64(2), int64(3), object(5)
memory usage: 4.0+ KB

In [16]:
#2 c

(df.shape[0])

50

In [18]:
#2 d
df.shape[1]

10

In [23]:
#2 e
df.memory_usage(deep=True)

Index           132
student_id      400
name           2693
gender         2702
department     2936
attendance      400
marks           400
age             400
semester        400
city           2825
scholarship    2575
dtype: int64

In [24]:
#Q3
df.columns

Index(['student_id', 'name', 'gender', 'department', 'attendance', 'marks',
       'age', 'semester', 'city', 'scholarship'],
      dtype='object')

In [28]:
#Q4 A
df.isnull().sum()

student_id      0
name            0
gender          0
department      0
attendance      0
marks          26
age            22
semester        0
city            0
scholarship     0
dtype: int64

In [29]:
#Q4 B
num_cols = df.select_dtypes(include=['int64','float64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

In [30]:
#Q4 C
cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

print(df.isnull().sum())

student_id     0
name           0
gender         0
department     0
attendance     0
marks          0
age            0
semester       0
city           0
scholarship    0
dtype: int64

/tmp/ipykernel_7199/2505152813.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [31]:
#Q5
df.mean(numeric_only=True)

student_id    25.500000
attendance    80.380000
marks         57.041667
age           21.714286
semester       3.260000
dtype: float64