<a href="https://colab.research.google.com/github/Edwinshajan2006/data-science-/blob/main/PANDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#!pip   install pandas

In [2]:
import pandas as pd
import numpy as np

In [4]:

df = pd.read_excel("/content/students_eda_dataset.xlsx")

In [5]:
# Q1 A

df.head()

,student_id,name,gender,department,attendance,marks,age,semester,city,scholarship
0,1,Rahul,Male,Mechanical,95,NaN,NaN,5,Thrissur,No
1,2,Anu,Male,Civil,62,NaN,18.0,1,Calicut,No
2,3,Vishnu,Male,Computer Science,90,36.0,NaN,1,Calicut,Yes
3,4,Sachin,Male,Computer Science,85,90.0,23.0,5,Kochi,No
4,5,Vimal,Female,Civil,99,NaN,NaN,1,Trivandrum,Yes

In [6]:
#Q1 B

df.tail()

,student_id,name,gender,department,attendance,marks,age,semester,city,scholarship
45,46,Vimal,Female,Mechanical,85,77.0,NaN,2,Kochi,Yes
46,47,Neha,Male,Civil,60,NaN,25.0,1,Calicut,Yes
47,48,Arjun,Male,Civil,73,36.0,25.0,6,Thrissur,No
48,49,Vimal,Female,Mechanical,80,74.0,25.0,4,Trivandrum,Yes
49,50,Pooja,Male,Electrical,62,NaN,NaN,4,Trivandrum,Yes

In [7]:
#Q1 C

df.shape

(50, 10)